// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";
import { ScreenVariantProvider } from "../components/plasmic/pro_layout_panel_landing_pgae/PlasmicGlobalVariant__Screen";
import { PlasmicHome } from "../components/plasmic/mr_biscuit_site/PlasmicHome";
import { useRouter } from "next/router";

function Home() {

  return (
    
    <ph.PageParamsProvider params={useRouter().query} query={useRouter().query}>
      
      <PlasmicHome />
    </ph.PageParamsProvider>
  );
}

export default Home;
